### ISSUE TITLE
Bug with bstr

### ISSUE THREAD

**Issue by DJATOM** [Frederick888/php-bencode#2] opened 2017-06-17 08:15 UTC
I tried to implement tracker response with your library, but faced a problem with ipv6 field. For some reason bstr shrinking compacted ipv6 data to 6 bytes. And it's all good with ipv4 compacted peers. 
Here's the script to reproduce that bug:
```<?php
$torr_seeds = 4;
$torr_leechs = 2;
$times_completed = 11;
$announce_interval = 420;
$announce_wait = 10;
$peerlist = "";
$peerlist6 = "";
$ipdata = [
	["ip"=>"10.31.31.240", "port"=>20000],
	["ip"=>"10.13.31.244", "port"=>52345],
	["ip"=>"10.13.31.1", "port"=>6881]
];
$ip6data = [
	["ip"=>"2a01:320:64ad::240", "port"=>20000],
	["ip"=>"2a01:320:64ad::244", "port"=>52345],
	["ip"=>"2a01:320:64ad::1", "port"=>6881]
];
foreach ($ipdata as $ipport_pair) {
	$octet = explode(".", $ipport_pair["ip"]);
    $peerlist .= pack("C*", $octet[0], $octet[1], $octet[2], $octet[3]) . pack("n", (int)$ipport_pair["port"]);
}

foreach ($ip6data as $ipport_pair) {
	$peerlist6 .= pack("H32n", bin2hex(inet_pton($ipport_pair["ip"])), (int)$ipport_pair["port"]);
}
	
$response = new bdict();
$response->set("complete", new bint($torr_seeds));
$response->set("incomplete", new bint($torr_leechs));
$response->set("downloaded", new bint($times_completed));
$response->set("interval", new bint($announce_interval));
$response->set("min interval", new bint($announce_wait));
$response->set("peers", new bstr($peerlist));
$response->set("peers6", new bstr($peerlist6));
var_dump($response->to_meta_array(), $peerlist, $peerlist6);
echo "\n";
```

I'm using last dev build, if that matters.

**Comment by Frederick888** [comment] 2017-06-17 10:17
Thanks for reporting.

The cause was that null characters were not correctly handled. I have just pushed the fixes to `dev` branch, could you please test it again?

**Comment by DJATOM** [comment] 2017-06-17 10:34
Tested. With var_dump((string)new bstr($peerlist6)); we get full string, but with full code still
```    ["peers6"]=>
    array(3) {
      ["_type"]=>
      string(4) "bstr"
      ["_length"]=>
      int(57)
      ["_data"]=>
      string(6) "* d▒"
    }
```
----
Forgot to test it in the tracker code, it works. Thank you for the fix.

**Comment by Frederick888** [comment] 2017-06-17 11:38
@DJATOM LOL I feel shame for this... didn't think a bit about null characters while writing this plugin. Just pushed to `dev` and tested on my own. Could you please double check it?

**Comment by DJATOM** [comment] 2017-06-17 11:55
Affirmative.
Thanks again for fast fix! :)

**Comment by Frederick888** [comment] 2017-06-17 11:56
@DJATOM Please do not close this issue for the time being. I just noticed that if a key of bdict contains NULL, there will be problems when encoding it. I'll fix it asap and close this issue then.

**Comment by Frederick888** [comment] 2017-06-17 12:20
I have fixed the found issues and published [a new release](https://github.com/Frederick888/php-bencode/releases/tag/v1.2.2).

Many thanks.

**Closed as completed by Frederick888** 2017-06-17 12:20 UTC
